name: Build and Push Docker Image

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up version
      run: echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag davidmdlp/site_david:${IMAGE_VERSION}
        docker tag davidmdlp/site_david:${IMAGE_VERSION} davidmdlp/site_david:latest

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u davidmdlp --password-stdin

    - name: Push image to Docker Hub
      run: |
        docker push davidmdlp/site_david:${IMAGE_VERSION}
        docker push davidmdlp/site_david:latest
